name: Resuable CodQL Security Scan Workflow

on:
  workflow_call:
    inputs:
      
      runs-on:
        description: |
                       CodeQL runs on ubuntu-latest, windows-latest, and macos-latest
        default: ubuntu-latest
        type: string
      
      language:
        description: |
                       To define the languages in your repo that are analyzed.
        #default: ${{ toJson(language) }}
        #required: true
        type: string
      
      config-file:
        description: |
                       If you wish to specify custom queries, you can do so here or in a config file.
                       By default, queries listed here will override any specified in a config file.
                       Prefix the list here with "+" to use these queries and those in the config file.
        type: string
      
      queries:
        description: |
                       By default, queries listed here will override any specified in a config file.
                       Prefix the list here with "+" to use these queries and those in the config file.
                       Details on CodeQL's query packs refer to : 
                       https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
        type: string
      
      auto-build:
        description: |
                       Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
                       If this step fails, then you should remove it and run the build manually 
                       using custom-build yml file.
        default: true
        type: boolean
      
      custom-build:
        description: |
                       Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
                       If this step fails, then you should remove it and run the build manually 
                       using custom-build file. This can also be a path to the executable file.
        type: string
      
      severity:
        description: |
                       Set the severity levels which to set the threshold. All previous 
                       severities are included so selecting 'error' also selects 'critical' and 
                       'high' along with 'error'.
        default: error
        type: string
      
      repository:
        description: |
                       Repository owner/name.
                       This can be setup using a separate repository to the one being analysed 
                       for security compliance
        default: ${{ github.repository }}
        type: string
      
      token:
        description: |
                       GitHub Personal Access Token to access the GitHub API.
                       Secret Scanning and Dependabot do not allow their resources to be
                       exposed to Actions so this might need to be set using a token that has 
                       the ability to access the resources
        default: ${{ github.token }}
        type: string
      
      ref:
        description: GitHub Ref
        default: ${{ github.ref }}
        type: string
      
      action:
        description: |
                       [optional] What course of action to take upon discovering security issues that pass
                       threshold?
        default: break
        type: string
      
      policy:
        description: |
                       The owner/repo of where the policy is stored
                       This generally is primarily used for a single repository that defines 
                       your organizations security policy
        type: string
      
      policy-path:
        description: |
                       Policy as Code file path (including path in repo)
                       The path where the policy lives. This might be in either the current 
                       repository or in a remote repository.
        type: string
      
      policy-branch:
        description: |
                       Policy as Code branch
                       The branch you want to target using `policy` argument
        default: main
        type: string
      
      argvs:
        description: |
                       [optional] Additional Arguments
        type: string
jobs:
  # CodeQL
  codeql:
    name: CodeQL Analyze
    # CodeQL runs on ubuntu-latest, windows-latest, and macos-latest
    runs-on: ${{ inputs.runs-on }}
    
    permissions:
      # required for all workflows
      security-events: write
      
      # only required for workflows in private repositories
      actions: read
      contents: read
    
    #strategy:
      #fail-fast: false
      #matrix:
         #include:
           #- language: ${{ inputs.language }}
         # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
         # Learn more about CodeQL language support at https://aka.ms/codeql-docs/language-support
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ inputs.language }} # comment this if using matrix & uncomment the below line
        #languages: ${{ matrix.language }} if using matrix
        config-file: ${{ inputs.config-file }} # If you wish to specify custom queries, you can do so here or in a config file.
        queries: ${{ inputs.config-file }} # By default, queries listed here will override any specified in a config file.
        # Prefix the list here with "+" to use these queries and those in the config file.
        # Details on CodeQL's query packs refer to : https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
        # queries: security-extended,security-and-quality

    # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
    # If this step fails, then you should remove it and run the build manually (see below)
    - name: AutoBuild
      if: ${{ inputs.auto-build == true }}
      uses: github/codeql-action/autobuild@v2
      
    - name: CustomBuild
      if: ${{ inputs.auto-build == false }}
      run: |
             echo "Run, Build Application using script"
             ${{ inputs.custom-build }}
      
    # ℹ️ Command-line programs to run using the OS shell.
    # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun

    #   If the Autobuild fails above, remove it and uncomment the following three lines. 
    #   modify them (or add more) to build your code if your project, please refer to the EXAMPLE below for guidance.

    # - run: |
    #   echo "Run, Build Application using script"
    #   ./location_of_script_within_repo/buildscript.sh
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
  
  # Compliance check
  compliance:
    runs-on: ubuntu-latest

    needs: [ codeql ]

    steps:
    - name: Advance Security Compliance Action
      uses: GeekMasher/advanced-security-compliance@main
      with:
        severity: error
        repository: GeekMasher/advanced-security-compliance
        policy: GeekMasher/security-queries
        policy-path: policies/default.yml
        policy-branch: main
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: refs/heads/main
        action: break
        #argvs: '--disable-secret-scanning --disable-dependabot'
        
        
