name: Resuable Security Scan Workflow

on:
  workflow_call:
    inputs:
      severity:
        description: |
                       Set the severity levels which to set the threshold. All previous 
                       severities are included so selecting 'error' also selects 'critical' and 
                       'high' along with 'error'.
        default: error
      repository:
        description: |
                       Repository owner/name.
                       This can be setup using a separate repository to the one being analysed 
                       for security compliance
        default: ${{ github.repository }}
      token:
        description: |
                       GitHub Personal Access Token to access the GitHub API.
                       Secret Scanning and Dependabot do not allow their resources to be
                       exposed to Actions so this might need to be set using a token that has 
                       the ability to access the resources
        default: ${{ github.token }}
      ref:
        description: GitHub Ref
        default: ${{ github.ref }}
      action:
        description: |
                       [optional] What course of action to take upon discovering security issues that pass
                       threshold?
        default: break
      policy:
        description: |
                       The owner/repo of where the policy is stored
                       This generally is primarily used for a single repository that defines 
                       your organizations security policy
      policy-path:
        description: |
                       Policy as Code file path (including path in repo)
                       The path where the policy lives. This might be in either the current 
                       repository or in a remote repository.
      policy-branch:
        description: |
                       Policy as Code branch
                       The branch you want to target using `policy` argument
        default: main
      argvs:
        description: |
                       [optional] Additional Arguments

jobs:
  # CodeQL
  codeql:
    runs-on: ubuntu-latest

   strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
  
  # Compliance check
  compliance:
    runs-on: ubuntu-latest

    needs: [ codeql ]

    steps:
    - name: Advance Security Compliance Action
      uses: GeekMasher/advanced-security-compliance@policy
      with:
        policy: GeekMasher/security-queries
        policy-path: policies/default.yml
